import type { Character } from '~/types/character'
import type { Rulepack } from '~/types/rulepack'

export const validCharacter: Character = {
  id: 'char-001',
  name: 'Aldric Brightblade',
  race: 'human',
  background: 'soldier',
  classes: [{ classId: 'fighter', level: 1 }],
  experiencePoints: 0,
  inspiration: false,
  abilityScores: { str: 16, dex: 14, con: 15, int: 10, wis: 12, cha: 8 },
  abilityScoreOverrides: {},
  hp: { max: 12, current: 12, temp: 0 },
  armorClass: 16,
  speeds: { walk: 30 },
  initiative: null,
  hitDice: { total: 1, remaining: 1, die: 'd10' },
  deathSaves: { successes: 0, failures: 0 },
  conditions: [],
  savingThrowProficiencies: ['str', 'con'],
  skillProficiencies: {
    acrobatics: 0, animalHandling: 0, arcana: 0, athletics: 1,
    deception: 0, history: 0, insight: 0, intimidation: 0,
    investigation: 0, medicine: 0, nature: 0, perception: 1,
    performance: 0, persuasion: 0, religion: 0, sleightOfHand: 0,
    stealth: 0, survival: 0,
  },
  otherProficiencies: ['light armor', 'medium armor', 'heavy armor'],
  attacks: [],
  spellSlots: {
    1: { max: 0, used: 0 },
    2: { max: 0, used: 0 },
    3: { max: 0, used: 0 },
    4: { max: 0, used: 0 },
    5: { max: 0, used: 0 },
    6: { max: 0, used: 0 },
    7: { max: 0, used: 0 },
    8: { max: 0, used: 0 },
    9: { max: 0, used: 0 },
  },
  spells: [],
  features: [],
  equipment: [],
  currency: { cp: 0, sp: 0, ep: 0, gp: 10, pp: 0 },
  notes: '',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  rulepackIds: ['srd-5.1'],
}

export const fighterRulepack: Rulepack = {
  id: 'test-pack',
  name: 'Test Pack',
  version: '1.0.0',
  races: [],
  classes: [
    {
      id: 'fighter',
      name: 'Fighter',
      hitDie: 'd10',
      primaryAbility: ['str', 'dex'],
      savingThrowProficiencies: ['str', 'con'],
      armorProficiencies: ['all armor', 'shields'],
      weaponProficiencies: ['simple weapons', 'martial weapons'],
      toolProficiencies: [],
      skillChoices: {
        count: 2,
        from: ['acrobatics', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival'],
      },
      levels: [
        {
          level: 1,
          proficiencyBonus: 2,
          features: ['Fighting Style', 'Second Wind'],
          levelUpEvents: [],
        },
        {
          level: 2,
          proficiencyBonus: 2,
          features: ['Action Surge'],
          levelUpEvents: [],
        },
        {
          level: 4,
          proficiencyBonus: 2,
          features: ['Ability Score Improvement'],
          levelUpEvents: [{ type: 'ABILITY_SCORE_IMPROVEMENT', points: 2 }],
        },
      ],
    },
  ],
  backgrounds: [],
  feats: [],
  spells: [],
}
